all: 
	Rscript -e "source('0-ensemble-functions.R')"
	Rscript -e "source('1-read-old-ram-fits.R')"
	Rscript -e "source('2-merge-ram-fits.R')"
	Rscript -e "source('3-load-sim-data.R')"
	Rscript -e "source('4-add-spectral.R')"
	Rscript -e "source('5-simulation-ensembles.R')"
	Rscript -e "source('6-sim-to-ram.R')"
	Rscript -e "source('7-plot-sims.R')"
	Rscript -e "source('8-main-figs.R')"
	Rscript -e "source('8-motivate-fig.R')"
	Rscript -e "source('9-output-values.R')"

